### PR TITLE
fix: inject tracing headers

### LINKED ISSUE #143: issues with galoy client
Headers need to be injected for every call (not just tx list). And need to use rustle.

There are now 2 different request clients being used in `Galoy-client`.
The `inner` one https://github.com/GaloyMoney/stablesats-rs/blob/main/galoy-client/src/client/mod.rs#L35
which is configured to use rustls https://github.com/GaloyMoney/stablesats-rs/blob/main/galoy-client/src/client/mod.rs#L62.
And another one that only gets created during `transactions_list` https://github.com/GaloyMoney/stablesats-rs/blob/b4b882d39d8ebb3f5d62f37816517bbff9fd20a3/galoy-client/src/client/mod.rs#L178-L183.

Obviously we should only have 1 client that we use internally and we need to add the headers to every call. Having 2 different code paths that configures the clients is no good because of the duplication - it has led to stablesats breaking on staging https://ui.honeycomb.io/galoy/datasets/galoy-staging/result/zc1TxpVM2EE

### PR DESCRIPTION
**Pull request by enigbe**
## What this PR does?
- Injects tracing headers in all requests
- Ensures there is only one request client

## Related issue
- Fixes #143

### CODE REVIEW

File: galoy-client/src/client/mod.rs [hunk 1]
```diff
@@ -328,27 +308,44 @@ impl GaloyClient {
...
+        let result = response_data.ok_or_else(|| {
+            GaloyClientError::GraphQLApi("Empty `onChainTxFee` in response data".to_string())
+        })?;
 
         let onchain_tx_fee = StablesatsTxFee::try_from(result)?;
 
         Ok(onchain_tx_fee)
     }
+
+    async fn traced_gql_request<Q: GraphQLQuery, U: reqwest::IntoUrl>(
```
Comment (bodymindarts) [inline galoy-client/src/client/mod.rs:333]: if you make this an instance method you could avoid the duplication of passing in `self.client` and `self.config.api` everywhere - not a big deal.

**Review by bodymindarts — APPROVED** [review]
