### PR TITLE
fix: galoy client error return

### LINKED ISSUE #115: galoy client not returning errors
When gql returns an error its not being passed back to the caller.

### PR DESCRIPTION
**Pull request by enigbe**
## What this PR does?
- Introduces `GrapgQLNested` and `GrapgQLTopLevel`  error variants from the Graphql API
- Propagates these errors to `GaloyClientError`

## Related Issue
- fixes #115

### CODE REVIEW

File: galoy-client/src/error.rs [hunk 1]
```diff
@@ -11,3 +17,30 @@ pub enum GaloyClientError {
     #[error("GaloyClientError - Authentication: {0}")]
     Authentication(String),
 }
+
+#[derive(Debug, Deserialize)]
+pub struct InnerError {
```
Comment (bodymindarts) [inline galoy-client/src/error.rs:22]: Why are these individual structs and not part of `GaloyClientError` enum?
I'm thinking the `GraphQLApi(String),` variant should simply be extended to have more fields or something like that.
Or perhaps another variant `GraphQLResponseError` but not individual structs - seems very strange.
